### PR TITLE
debian instructions link

### PR DESCRIPTION
**Pull request by ederag**
instructions proposed by Gerald Jansen in #369

### CODE REVIEW

**Comment by GeraldJansen** [comment]
This is okay as a temporary solution. Now that the instructions are confirmed by a few others it might be better to put them on a wiki page of the hamster project and link to that. (note: detailled -> detailed).

**Comment by ederag** [comment]
Sure, please feel free to move the page to the hamster project wiki if you want.
And thanks for catching the typo !

**Comment by GeraldJansen** [comment]
Ok, I've moved the instructions to the hamster project wiki.

**Comment by ederag** [comment]
Thanks gain !

**Pull request merged**
