### PR TITLE
fix bug preventing removal of autocompletion tags

### PR DESCRIPTION
**Pull request by GeraldJansen**
This fixes a tiny bug in concerning tag autocomplete flags (1 vs. 'true') in the sqlite database, fixed here by checking for not 'false'. See #238.

### CODE REVIEW

**Comment by ederag** [comment]
Thanks for providing a fix.
Checking for non-equality seems less safe than for equality.
(equality matches one case, while non-equality matches any other type instances)

Checking for `"true" or 1` would not help much,
as this feels like something weird is going on.
What triggered the change from true/false to 1 in the first place ?

**Comment by GeraldJansen** [comment]
The code is inconsistent. New tags created from adding facts get 1. Recovered tags that were 'false' get set to 'true' (in preferences iirc). At any rate, in existing databases, both 1 and 'true' may be in the DB, whereas on the negative side there is only 'false'. I found this check for autocomplete != 'false' at another place in the code.

**Comment by ederag** [comment]
> The code is inconsistent. New tags created from adding facts get 1.

This does seem to be explicitly set. Is that a default value ? Yes:

Using `sqlitebrowser ~/.local/share/hamster-applet/hamster.db`, in `database structure`,
for tags:
```sql
CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
                   name TEXT NOT NULL, autocomplete BOOL DEFAULT true)
```
so `autocomplete` is expected to be boolean, not text.
Note: `BOOL` is not defined in sqlite, [only `BOOLEAN` is](https://www.sqlite.org/datatype3.html#affname).
Besides, python `sqlite3` has [no adapter for booleans](https://docs.python.org/3.7/library/sqlite3.html?highlight=sqlite3#introduction).

A `CHECK` would have prevented this, see
https://stackoverflow.com/a/22186315/3565696
http://www.sqlite.org/lang_createtable.html#ckconst
No; that would break the database compatibility.

> I found this check for autocomplete != 'false' at another place in the code.

Indeed, found one in `__get_tags` but that is read only, not as risky as writing.

Would replacing all the settings to `"true"`/`"false" to be `1`/`0` right now,
break previous versions ?
(using the same database with previous versions is part of the compatibility constraint) 
Not for this line that was [not changed in ten 10 years](https://github.com/projecthamster/hamster/blame/46954af249f393f6baebe0ff3934bb1331d2ae8e/src/hamster/storage/db.py#L159)
https://github.com/projecthamster/hamster/blob/46954af249f393f6baebe0ff3934bb1331d2ae8e/src/hamster/storage/db.py#L159
But this one would be affected:
https://github.com/projecthamster/hamster/blob/46954af249f393f6baebe0ff3934bb1331d2ae8e/src/hamster/storage/db.py#L172

So what about replacing the conditionals 
`== "true"` or `!= "false"` 
to 
`in (1, "true")`
and `== "false"` to `in (0, "false")`
both in the sql queries and in the python conditionals,
to get something safe and backward compatible,
and drop the "true"/"false" later ?

**Comment by GeraldJansen** [comment]
Too many questions. The simple bug fix is good enough for me. Please do as you see fit with this PR.

**Comment by ederag** [comment]
Sorry, understood :smile: 
and you are right that your fix could be used.
The last proposition just feels even safer.
The rest were mainly notes taken while investigating.
Only the last question really matters.

**Comment by GeraldJansen** [comment]
If you prefer to put `in (1, 'true')` and `in (0, 'false')` everywhere, please do so. No offence taken. I prefer to not discuss this further.

**Pull request merged**
