### PR TITLE
Date/time tweaks

### PR DESCRIPTION
**Pull request by GeraldJansen**
Improve consistency in date/time handling (#428) by:

* switching to ISO date format (%Y-%m-%d) in lib/* to be consistent with hamster-cli usage
* rounding (i.e. truncating) all activity start/end timestamps to the minute
** note that this only affects new and/or edited activities in the database

### CODE REVIEW

**Comment by GeraldJansen** [comment]
Found bug:
```
$ ./hamster-cli export tsv 2019-08-17 2019-08-19
Traceback (most recent call last):
...
  File "./hamster-cli", line 121, in parse_datetime_range
    to_time(fragments['time1']) or now)
TypeError: combine() argument 2 must be datetime.time, not datetime.datetime
```

**Comment by GeraldJansen** [comment]
[tests]$ python3 stuff_test.py 
.............
----------------------------------------------------------------------
Ran 13 tests in 0.013s

OK

**Comment by GeraldJansen** [comment]
Okay for dt_now -> hamster_now and additional changes (db/storage.py, widgets/activityentry.py, widgets/dayline.py, tests/stuff_tests.py). stuff_tests.py still OK.

I don't agree about changing dt.datetime.now to stuff.hamster_now for idle.py and widgets/desktop.py, partly because they seem to depend on accuracy to seconds and partly because I don't know how to test them.

I'm unsure whether hamster_today should use hamster_now (i.e. truncated times). From my testing it does not affect the start/end times stored in hamster.db, which was the main focus of this pull request.

[Aside: My availability will be very limited for the next month or so, so please proceed with this as you see fit.]

**Comment by ederag** [comment]
> I don't agree about changing dt.datetime.now to stuff.hamster_now for idle.py and widgets/desktop.py, partly because they seem to depend on accuracy to seconds <...>

You are right again, they do seem to need second accuracy.
I took the liberty to change some spaces, 
and to make `hamster_today` use `hamster_now`, 
as it does not seem to harm and feel more consistent to me.


> My availability will be very limited for the next month or so, so please proceed with this as you see fit.

Your PR seems clean, and improves a lot the consistency of hamster;
 it is really tempting to include it in our upcoming v3.0.
To be reviewed again in the next few days.

**Comment by ederag** [comment]
That still looks very good, to be included in v3.0, thanks again !

**Pull request merged**
