### PR TITLE
build: Install the desktop file

### PR DESCRIPTION
**Pull request by bochecha**
Not having this makes it a bit harder to launch the app. :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by ederag** [comment]
Indeed, thanks !

Side note: `hamster.desktop` (and hamster-windows-service) should be improved to comply with
https://wiki.gnome.org/HowDoI/DBusApplicationLaunching
Would you by chance also know how to do all this cleanly ?

**Comment by bochecha** [comment]
>  Would you by chance also know how to do all this cleanly ?

I'm not sure. The usual approach is to use GApplication (through GtkApplication) and its `--gapplication-service` command-line option so that the app is started as a background service. Then there are a few trivial things to do with the desktop file, and you're done.

However in the case of Hamster, the DBus service seems to be completely separated from the app if I understood correctly? (they are different processes, different executables, …)

I don't know how to handle such a case. :confused:

**Comment by ederag** [comment]
> The usual approach is to use GApplication (through GtkApplication) and its --gapplication-service command-line option so that the app is started as a background service. Then there are a few trivial things to do with the desktop file, and you're done.

Thanks for the confirmation, that's exactly the goal.

> The DBus service seems to be completely separated from the app if I understood correctly?

Opened #533 to discuss this further.

Reading `hamster-cli.py` again, it is work in progress,
the structure is unclear for a new reader right now.
I'll try this week-end and call for help or review.

**Comment by ederag** [comment]
@bochecha #536 made progress, but now it's stuck. 
Help would be much appreciated, if you have time this week.
Please do tell on #533 if you start working on it, to avoid duplicating efforts.

**Pull request merged**
