### PR TITLE
Verbatim database read/write

### PR DESCRIPTION
**Pull request by ederag**
With this PR database read/write is done verbatim, without any parsing involved.
This makes a clear separation of concerns.
It partially solves #280 and #423,
although that requires renouncing to the quickness of the cmdline input, until #465 is solved.

This change should not affect the existing dbus interface (old functions have been kept).
The new `AddFactVerbatim` is strongly encouraged if the caller has separate fields.
The old `AddFact` will remain so that passing a single string will remain possible,
to be interpreted by `Fact.parse` on the hamster side.

Unsorted (no category) facts are not supported yet (forthcoming PR almost ready).

### CODE REVIEW

**Comment by ederag** [comment]
@GeraldJansen Could it be that `hamster-service` from a previous version is installed ?
In this case, launching `hamster-cli` queries dbus through `client.py`,
that automatically relaunches the installed `hamster-service`, 
which lacks the new `AddFactVerbatim` method.

Could you try to launch the new hamster-service first ?
```bash
pkill -ef hamster.*service
./hamster-service
./hamster-cli track a long, hard furrow
```
If a service is already found running, it is used.

**Comment by ederag** [comment]
By the way, using your example gives an "a" in activity, the rest is lost.
But that was already the case previously (checked with 5f782f6fecb0c46db2332ce6c16bf287a34379dd).
`Fact.parse` will be reworked to make it usable for command line parsing, after v3.0.

**Comment by GeraldJansen** [comment]
> Could it be that hamster-service from a previous version is installed ?

Right, of course. Sorry for the noise.

OT.  Now getting this error message every minute on update:
`hamster.lib.desktop - ERROR - Error while refreshing: 'Fact' object is not subscriptable`

On a plus note, I don't find any noticeable slowdown in auto-completion from the cmdline. Its still very snappy for me.

**Comment by ederag** [comment]
Thanks, this one slipped under the radar.
1aefbba2d5ef9fcc5e6ba1d8cf96069893a4aaea is a blind guess. Is it silent now ?
Need to find who is calling `desktop.py`...

**Comment by GeraldJansen** [comment]
> 1aefbba is a blind guess. Is it silent now ?
Yes. Good guess.

**Comment by GeraldJansen** [comment]
A small bug (edge case?): if I update an activity that has a category, clear the category and save, the saved fact still has the old category, not Unsorted.

**Comment by ederag** [comment]
Indeed, that's because after clear the fact has no category.
> Unsorted (no category) facts are not supported yet (forthcoming PR almost ready).

That needs a 3 lines only fix, ready, but unfortunately it is slightly breaking the dbus interface:
`GetFact` and `GetFacts` would return an empty string instead of "Unsorted".
You may try this [fix-unsorted](https://github.com/ederag/hamster/tree/fix-unsorted) branch,
but please do not base anything on it, as more rebase are expected.
What do you think ?

**Comment by GeraldJansen** [comment]
No further comment. As an aside, I've always found the @Unsorted presence in the cmdline strange and unsightly. I always assign a real category.

**Pull request merged**
