### PR TITLE
add total duration in 'hamster list' command

### PR DESCRIPTION
**Pull request by madtibo**
Add a total time line at the bottom of the 'hamster list' command.

### CODE REVIEW

**Comment by ederag** [comment]
Thanks for your contribution.
It would be better to sum deltas (that are in seconds), 
to avoid rounding errors such as https://github.com/projecthamster/hamster/issues/76.

**Comment by madtibo** [comment]
I saved the duration in seconds, is it better that way?

**Comment by ederag** [comment]
What about c71aaf7226d243460e570f5b974688de7915bdc1 ?
Totals would use the same "human" format as in the duration column.

**Comment by ederag** [comment]
Thanks for contributing !

**Pull request merged**
