### PR TITLE
Add taskwarrior integration

### PR DESCRIPTION
**Pull request by sanjayankur31**
Deleting the remote branch closed ticket #170. This is a re-based pull request.

### CODE REVIEW

**Comment by Velmont** [comment]
Is this held up?

**Comment by sanjayankur31** [comment]
Hrm, seems like it is. I thought it'd been merged..

**Comment by Velmont** [comment]
@toupeira Could you please review and merge, or point out why it's held up?

**Comment by toupeira** [comment]
Sorry about that, not sure what I was thinking when posting that comment :) Looks fine to me, I'll merge it.

**Pull request merged**
