### PR TITLE
compute and display total period tracked time

### PR DESCRIPTION
**Pull request by madtibo**
Hello,

I upgraded to buster. I moved from standard debian version to git master version.
I really missed the grand total from the statistics view so here is a proposal to add it back.

Cheers,
Thibaut

### CODE REVIEW

**Comment by ederag** [comment]
Thank you very much for this nice contribution.
A similar addition (commit https://github.com/projecthamster/hamster/pull/363/commits/4cc66434cc1c74749976a483ee2f9edaad9efb3b)
was buried inside PR #363 that should be merged this week-end
(I [just received](https://github.com/projecthamster/hamster-gtk/issues/228#issuecomment-440579659) write access to this repo).

**Comment by madtibo** [comment]
I am not the only one who miss the grand total then :-p

**Comment by ederag** [comment]
Closing, now that PR #363 has been merged.
@madtibo thanks again for contributing !

**Comment by madtibo** [comment]
You're welcome.
I was thinking of displaying the day total as well. 
Maybe a new PR sometime :)

**Comment by ederag** [comment]
> I was thinking of displaying the day total as well.

Good idea ;-) 
But please try the updated master.
The day total is already displayed (at the beginning of the totals line, after the `Total: ` label).

**Pull request closed without merging**
