### PR TITLE
Streamline installation instructions

### PR DESCRIPTION
**Pull request by ederag**
As adequately noted in https://github.com/projecthamster/hamster/issues/418#issuecomment-567891068, the installation instructions are not clear enough.

@tchama Is [this proposition](https://github.com/projecthamster/hamster/blob/98b8de3a92ad72b1d5f4aab395bfc5db77b9e405/README.md) better ? Thanks for helping ironing out the installations instructions.

### CODE REVIEW

**Comment by tchama** [comment]
I was able to follow the instructions of the main module, but then when I launch hamster, I get an error that I understand, such as the fact that one or more components are missing in my installation.

On the page https://github.com/projecthamster there are 6 pinned repositories. The main obstacle is to know which module I need, and what they are used for. 
I have the impression that there is a lack of an overview of these modules, to know what they are for, which ones are needed, in which order they should be compiled, etc.

**Comment by ederag** [comment]
This repository is monolithic (single module),
no need for the `hamster-*` modules that are part of the separate "rewrite" project (currently stalled).

Could you please paste the error message ?

**Comment by tchama** [comment]
ok. Here is my [hamster_install_log.txt](https://github.com/projecthamster/hamster/files/3991351/hamster_install_log.txt).

After that I just tried to launch hamster
```
mat @ swan  ~
└─ $ ▶ hamster
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
ImportError: cannot import name 'client' from 'hamster' (/home/mat/.local/lib/python3.7/site-packages/hamster/__init__.py)
```
Thanks for trying to help me install it.

**Comment by ederag** [comment]
Thanks for the full log. It looks fine, installation is in the standard `/usr/lib/python3/dist-packages/`.
But at launch time, the import is looking into
`/home/mat/.local/lib/python3.7/site-packages/hamster`.
That is probably a remnant of a former installation attempt (maybe `pip install hamster-sqlite` ?).
You might try to move `/home/mat/.local/lib/python3.7/site-packages/hamster` out of the way.

**Comment by tchama** [comment]
> That is probably a remnant of a former installation attempt (maybe `pip install hamster-sqlite` ?)

That was it. I removed `hamster-sqlite` from the python packets. Hamster's launching now. I still have some hamster packets left in python. Should I take those out, too?
```
└─ $ ▶ pip3 list | grep hamster
hamster-cli            0.12.0       
hamster-gtk            0.11.0       
hamster-lib            0.13.2       
hamsterlib             0.1.0    
```
Thanks for the push.

**Comment by ederag** [comment]
Glad it works !
All 4 packages are from the hamster rewrite, and could be removed, as far as [hamster](https://github.com/projecthamster/hamster) is concerned.
But there should not be any conflict either, as they use different package names and DBus interface.

@elbenfreund [hamsterlib](https://pypi.org/project/hamsterlib/) looks like a failed attempt, superseeded by [hamster-lib](https://pypi.org/project/hamster-lib/) ?

**Pull request merged**
