### PR TITLE
Port to GSettings

### PR DESCRIPTION
**Pull request by bgamari**
This refactors the configuration infrastructure away from the deprecated
GConf library and towards GSettings.

### CODE REVIEW

**Comment by GeraldJansen** [comment]
Not sure about the importance of this build message:
```
./waf configure build
...
[126/126] Compiling data/hamster-time-tracker.desktop.in.in
feature 'glib2' does not exist - bind at least one method to it?     <===
[127/254] Compiling data/apps.hamster-time-tracker.gschema.xml.in
...
'build' finished successfully (1.708s)
```
and also 
```
sudo ./waf install
...
+ install /usr/share/hamster-time-tracker/stats.ui (from data/stats.ui)
feature 'glib2' does not exist - bind at least one method to it?      <===
+ install /usr/share/applications/hamster-time-tracker.desktop (from build/data/hamster-time-tracker.desktop)
...
'install' finished successfully (0.274s)
```
Then
```
 /usr/bin/hamster

(hamster:5992): GLib-GIO-ERROR **: 11:43:23.021: Settings schema 'apps.HamsterTimeTracker' is not installed
Trace/breakpoint trap (core dumped)
```

**Comment by ederag** [comment]
`glib2` has to be  [loaded](https://waf.io/apidocs/tools.html) first.
Probably add 
```python
conf.load('glib2')  # for gsettings schemas installation`
```
in the `wscript` file, `configure` method,
maybe replacing those lines
https://github.com/projecthamster/hamster/blob/2d58bf6a3a1b10f0dd632b9eb3fe714078e3597b/wscript#L26-L27

**Comment by GeraldJansen** [comment]
Works for me.

**Comment by bgamari** [comment]
The one thing that I wonder is whether we should rename the schema. I
realized only after I finished the patch that the schema name really
ought to rename the DBus name.

**Comment by ederag** [comment]
@bgamari The DBus interface should remain stable (`org.gnome.Hamster`)
https://github.com/projecthamster/hamster/blob/3375db55443359659468b2623a5cc8bb3cb3c910/src/hamster-service#L52
So we should keep this name.
Maybe one day this application will get back under the gnome organization umbrella;
that's not planned, but who knows.

@GeraldJansen Does it mean that we should rename the database directory to `hamster` as well ?

**Comment by GeraldJansen** [comment]
> Does it mean that we should rename the database directory to hamster as well ?

For me, .local/share/hamster-time-tracker is consistent with /usr/share/hamster-time-tracker and other installation directories and file names. Either rename everything to just hamster or use hamster-time-tracker consistently, I'd say.

**Comment by ederag** [comment]
> Either rename everything to just hamster or use hamster-time-tracker consistently

Agreed. 
Yet there might be good reasons to keep the more expressive `hamster-time-tracker` directories.
I'll file an issue to discuss that.

**Comment by ederag** [comment]
@GeraldJansen would you have time to implement the directory names changes (#472) and
thoroughly review this PR ?
This is very important indeed, and will get into v3.0,
but the parser update currently takes all my focus.

**Comment by GeraldJansen** [comment]
@ederag I'm willing to try.

**Comment by GeraldJansen** [comment]
@bgamari In #485 hamster-time-tracker has been renamed to hamster everywhere. This has caused a few conflicts with your PR. Would you mind rebasing on current master?

**Comment by ederag** [comment]
@GeraldJansen If @bgamari is not available at this time
(really hoping we did not lose such a valuable contributor), 
another workflow might suit you:
it is possible to branch from this PR,
merge (not rebase) upstream/master,
make additional changes,
and push them to your fork.
Then either 
make a [PR on the fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork), taking care to
select the [bgamari/hamster](https://github.com/bgamari/hamster) fork `gsettings` branch at the "compare across forks" step 
(that would allow both of you to discuss and converge there)
or
tell me here to cherry-pick your branch and push it for you to this PR
(you would remain the author of your commits IIUC), 
so that all the discussion stays there.

**Comment by GeraldJansen** [comment]
@ederag Well, I'm out of my depth here, both concerning advanced git techniques and gsettings. I've created a replacement PR (take 2) with a single additional commit (1e08ebe) which merges in current master and adds a couple minimal changes. If you prefer to add the last commit to this PR and close the other, that would be fine by me too.

**Comment by ederag** [comment]
That went well, thanks !
Next time you may just push, without creating any PR, and just give me your branch name
(or its last commit).

**Comment by GeraldJansen** [comment]
Tried to contact @bgamari also by private email but got no response. 
From my side I'd say this is good to go.

**Comment by ederag** [comment]
There are small issues remaining, to be reviewed this week-end or the next one.

**Comment by ederag** [comment]
external, desktop and idle have to be removed first (#493),
to start with a clean schema.

**Comment by GeraldJansen** [comment]
@ederag I am currently traveling and will not be able to work on this until January. Please feel free to proceed.

**Comment by ederag** [comment]
Sure, already started (that's why it was added to maintenance).
It was obvious you were unavailable, but it's good to know you are fine. Happy traveling !

**Comment by ederag** [comment]
@bgamari Your PR was great, only slightly polished.
Sliced in small commits to allow easy reversal,
but the [overall change](https://github.com/projecthamster/hamster/pull/470/files/9ce4e5b7596dd9377a686e1c39366d942b0001da..406b68ffaf3860d2b1539399b2b5cdbb737027ac)  with respect to your initial PR is very small.
You might want to try the [parser-updates-with-gsettings](https://github.com/ederag/hamster/tree/parser-updates-with-gsettings) branch that merges your PR into #482 .
> Note: the schema localization seems to follow the recommendations, but does not work yet.
Giving up.

Is it OK to merge ?

**Comment by ederag** [comment]
The schema localization works on openSUSE Leap-15.1, after an update of the french `po/fr.po`
and installation of hamster.
```bash
> LANGUAGE=fr gsettings describe org.gnome.Hamster last-report-folder
Le dernier répertoire utilisé pour enregistrer un rapport
```
@bgamari 
Merging so the snap package (created by @extraymond, initially in #418) can follow the `master` branch.
Please file an issue if anything is wrong.
Thanks again for the great contribution !

**Pull request merged**
