### PR TITLE
Resume last activity using Ctl-Space.

### PR DESCRIPTION
**Pull request by GeraldJansen**
This allows toggling the tracking of an activity on and off with Ctl-Space, as requested in #595.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
@GeraldJansen To make this PR merge again, I would do an interactive rebase, which shows you all of your commits that it will reapply during the rebase, so you can remove your flake8-fixing commit from the list (but maybe git can do that automatically if your changes were completely identical to the merged PR).

**Comment by GeraldJansen** [comment]
@matthijskooijman Thanks for the tip to rebase interactively. Done.

**Comment by GeraldJansen** [comment]
Closing out of impatience. Bye.

**Comment by GeraldJansen** [comment]
@matthijskooijman If you think it worthwhile, this PR could be reopened in order to close one more issue. I know feature requests are not a high priority but here the work is already done.

**Comment by matthijskooijman** [comment]
@GeraldJansen This sounds like a useful feature, so I would like to see it reopened. I can't seem to reopen it myself, because your branch or repo is deleted, though.

I also had a look over the code, which looks good to me. I haven't tested, though.

**Pull request closed without merging**
