### PR TITLE
Resume last activity using Ctl-Space.

### PR DESCRIPTION
**Pull request by GeraldJansen**
This allows toggling the tracking of an activity on and off with
Ctl-Space, as requested in #595.

### CODE REVIEW

**Comment by GeraldJansen** [comment]
@matthijskooijman This is an identical replacement for #620. There were problems with that PR because last year I deleted my github fork out of impatience. Sorry for the confusion.

**Comment by GeraldJansen** [comment]
I have just tested it again and am fairly confident it works as advertised. I also tested xfce4-hamster-plugin (current master) against this PR just to be sure I didn't muck up dbus functions. Nothing seems broken. Pinging @sh-zam who liked the earlier PR and @otto-dev who requested the feature to see if they did any testing.

**Comment by sh-zam** [comment]
> I have just tested it again and am fairly confident it works as advertised. I also tested xfce4-hamster-plugin (current master) against this PR just to be sure I didn't muck up dbus functions. Nothing seems broken. Pinging @sh-zam who liked the earlier PR and @otto-dev who requested the feature to see if they did any testing.

I've cherry-picked the previous patch locally and have been using it ever since it was created. So, yes it works just fine :)

**Comment by GeraldJansen** [comment]
Ping: anything holding up a merge on this one?

**Comment by matthijskooijman** [comment]
Good point, given two maintainers are involved, I think this can indeed be merged.

I did a quick test just now, seems to work as expected. One thing that was a bit surprising is that if you stop an activity and restart it immediately with ctrl+space, it creates a *new* fact that follows the previous fact directly (start time = stop time of previous fact). It seems I would have expected that it would instead continue the previous fact (I think this is what the gnome shell extension does when you stop and immediately restart the same activitity). However, given that this is really mostly a pathologic case (in real usecases you will have some time between stopping and restarting the activity, unless you accidentally stopped and want to resume), I don't think this is really important. So I'm going to go ahead and merge this, and we can always improve on this later if we think it is relevant enough.

**Pull request merged**
