### PR TITLE
Rename hamster-time-tracker to hamster everywhere

### PR DESCRIPTION
**Pull request by GeraldJansen**
Reduce confusion about hamster / hamster-time-tracker [/ hamster-applet] by renaming everything from hamster-time-tracker to simply hamster (#472). 

Renamed directories (including ~/.local/share/hamster), schemas, desktop files, icons, etc., etc..

(The only place "hamster-time-tracker" is left is in the comments of the translation *.po files.)

### CODE REVIEW

**Comment by ederag** [comment]
Everything is fine, merging, thanks !

Here is the backtrace issued when a former `hamster-service` has been left running,
mentioned here for reference:

```python
hamster
Traceback (most recent call last):
  File "/usr/bin/hamster", line 415, in <module>
    getattr(hamster_client, command)(*args.action_args)
  File "/usr/bin/hamster", line 157, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 148, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.gi.repository.GLib.Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/hamster-time-tracker/hamster-windows-service", line 39, in overview
  File "/usr/lib/python3/dist-packages/hamster/lib/configuration.py", line 150, in show
    dialog = self.get_dialog_class()(parent, **kwargs)
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 423, in __init__
    self.storage = hamster.client.Storage()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 70, in __init__
    self.range_pick = RangePick(stuff.hamster_today())
  File "/usr/lib/python3/dist-packages/hamster/widgets/dates.py", line 80, in __init__
  File "/usr/lib/python3/dist-packages/hamster/lib/configuration.py", line 90, in load_ui_file
    ui.add_from_file(os.path.join(runtime.data_dir, name))
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/usr/share/hamster-time-tracker/date_range.ui”: No such file or directory (4)
```

Simple fix:
`pkill -ef hamster`

**Comment by matthijskooijman** [comment]
Hm, just noticed this commit. In my Debian package in progress, I was actually planning to use `hamster-time-tracker` as a package name, since it is a bit more explicit than just `hamster`. In the light of this PR, I should maybe stick with `hamster` then.

@GeraldJansen, in the PR description, you say "confusion about hamster / hamster-time-tracker [/ hamster-applet]". I known hamster-applet is the old version, but what is the confusion with hamster-time-tracker exactly? Is there some other legacy version this should not be confused with? Or was this just because both `hamster` and `hamster-time-tracker` were used in different places?

**Comment by GeraldJansen** [comment]
It was indeed "just because both `hamster` and `hamster-time-tracker` were used in different places". 

The one down-side I've learned about this renaming is that web searches for just "hamster" are practically useless. Oh well.

**Comment by mwilck** [comment]
> The one down-side I've learned about this renaming is that web searches for just "hamster" are practically useless. Oh well.

Searches for "hamster time tracker" work.

**Comment by matthijskooijman** [comment]
> It was indeed "just because both hamster and hamster-time-tracker were used in different places".

Ok. I'll have to see about the Debian package, maybe I'll stick to hamster-time-tracker because it is more clear to users looking through the list, and takes up a smaller part of the available package namespace. That's for later anyway.

**Comment by mwilck** [comment]
We should leave it to distro maintainers how to name the package, as long as the name isn't derogatory for our project. Distributions can have various constraints wrt how packages can be named.

Under openSUSE, different package names have been used in the past. One reason was the confusion about the versioning; in the early days, there was a predecessor called `hamster-applet` in different distributions (including Debian), with version 2.91, which predated hamster 1.0 IIRC.

The good thing about `hamster-time-tracker` is that it would be found by people searching for a time tracker, even if they had no idea about "hamster" before.

**Pull request merged**
