### PR TITLE
Bump flatpak runtime version and deps

### PR DESCRIPTION
**Pull request by tchernobog**
Bump to latest GNOME Sdk/Platform version 40.

### CODE REVIEW

**Comment by tchernobog** [comment]
@matthijskooijman This is a relatively straightforward patch; could you consider merging it? The old runtime is deprecated.

**Comment by rabin-io** [comment]
I submitted Hamster to flathub, https://github.com/flathub/flathub/pull/2636
and it's available on FlatHub now, https://flathub.org/apps/details/org.gnome.Hamster

**Comment by aquaherd** [comment]
@rabin-io: Flathub seems to have gnome 41 whereas this here has 40 - if you could update this I would like to merge this if there are no objections.

**Comment by rabin-io** [comment]
Hi @aquaherd 

Maybe I didn't understand you request, 
do you want me to change the versions from 41 to 40 on the fluthub repo ?

**Comment by aquaherd** [comment]
> Hi @aquaherd
> 
> Maybe I didn't understand you request, do you want me to change the versions from 41 to 40 on the fluthub repo ?

No the other way round. It looks to me like your submit at the flathub repo is on 41 and this pull request is at 40. I might have misread that, though. If  both are in sync and nobody protests this I am going to merge it. If your submission and the pull request of @tchernobog have diverged then I would like to know what to do.

Fact is, I seem to have inherited write access to the repo and have some free time to spend but I have no idea what is going on here other than that nobody seems to want to merge these low risk things.

**Comment by rabin-io** [comment]
I think that @tchernobog need to bump the version in his commit/PR

**Comment by tchernobog** [comment]
Updated. I also prefer YAML to JSON for manifests, so I performed the conversion too as @rabin-io did.

**Comment by tchernobog** [comment]
It was necessary also to bump the version of the runner since GitHub stopped providing one for Ubuntu 16.04.
Now we should be good with CI too.

**Review by aquaherd — APPROVED** [review]
If no one protests I am going to merge this.

**Pull request merged**
