### PR TITLE
remove ederag from maintainers

### PR DESCRIPTION
**Pull request by ederag**
rationale: https://github.com/projecthamster/hamster/issues/574#issuecomment-593156136

### CODE REVIEW

**Comment by GeraldJansen** [comment]
@ederag Please do not rush like this.

**Comment by ederag** [comment]
Thanks for the support, really appreciated.

But this a cold and well thought decision.
I will not fight with @elbenfreund and those who do not see the wrong in his acts.
Life is too short.

And how could I continue in an organization owned by someone
who proved yesterday disrespect to me and the community
(as explained in https://github.com/projecthamster/hamster/issues/574#issuecomment-593172629).

No, the only way to continue is where I have full control.
[*meaning last resort control; 
I'd rather resign than go against the community will*]

**Comment by Forage** [comment]
Sad to see you go @ederag but I do would like to take the opportunity to thank you for all the time and effort you've put into the project to get it in an up-to-date usable state again! (thank GitHub for not limiting the amount of projects to track for releases ;) )

**Comment by extraymond** [comment]
@ederag Just caught up on this... 

All I can say is how I appreciate your steady and frequent efforts of bringing not only the project but people interested in hamster back. It's truly an welcoming experience to work with you in both understanding hamster and build the snap. Hope all the best for you.

**Pull request merged**
