### PR TITLE
python3 port + usability fixes

### PR DESCRIPTION
**Pull request by ederag**
hamster-time-tracker was dropped from openSUSE Leap15
https://www.reddit.com/r/openSUSE/comments/7zrj03/whats_the_best_time_tracker_on_tumbleweed/
The new development seemed to go well, but still claimed as alpha.
The [fork by gsobczyk](https://github.com/gsobczyk/hamster) had too many unresolved dependencies on Leap15.
The [master](https://github.com/projecthamster/hamster/commit/c3e5fb761c88fdecfd1566cac8b6836228a27cce) branch worked out of the box,
without python-gconf, and with the same hamster.db database.

Several usability fixes were needed though.
Now it seems more intuitive and consistent.
There is a python2 branch, but I'm now exclusively on the python3 branch.
There seems to be little chance to merge it back here,
so comments, issues and small PR are welcome in this [fork](https://github.com/ederag/hamster).
It will hopefully last only a few years, until the new hamster-* is stable.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
It'd be great if hamster was maintained again while the rewrite happens! :heart:

**Comment by elbenfreund** [comment]
I am in a bit of a rush right now, so here is the gist of it:
:heart: :+1: :tada: 

@ederag Thanks for reaching out via mail recently. As you correctly assumed, sadly I personally do not have any resources to spend on ``legacy hamster``. And so far noone else has steped up to the challenge.

As you have shown a willingness to actually invest work into this, as well as made a charming first impression I would be happy to accept you as the maintainer for the ``legacy hamyer`` repo and have you handle this by your own best judgement.

Before you accept this offer though: Please take a day or two for some soul searching as picking up the slack on the old code will without a doubt raise new expectations and there will be more work to come. So what I would ask is that you can be reasonably safe and willing to stick with the project for at least half a year. :) (I am the first to acknowledge that this is always easier said than done ;()

I am looking forward hearing from you and thank you for this awesome contribution.

**Comment by ederag** [comment]
> picking up the slack on the old code will without a doubt raise new expectations and there will be more work to come.

Thanks for the kind and wise words.
No fancy promises here: the legacy code is good, but I agree, hard to maintain.
So only little straightforward fixes are to be expected.
The goal is just to keep legacy hamster working on new platforms,
and allow users to continue to use this great tool,
until the rewrite is stable; that's where the main effort should go.

> So what I would ask is that you can be reasonably safe and willing to stick with the project for at least half a year. :)

It is my intent, but please note that write permissions to
[projecthamster/hamster](https://github.com/projecthamster/hamster) should be enough to maintain it.
So you keep full control of the project (including legacy hamster), of course.

**Comment by shaform** [comment]
Would it ever be possible to update the version 2.91.3 as well? Currently, I am using the instructions in https://github.com/projecthamster/hamster/issues/356 to install 2.91.3. But I am worried that one day this would no longer work for future versions of Ubuntu.

**Comment by ederag** [comment]
@shaform exactly. If you manage to install the old version, then it is currently the best choice,
There is no reason to worry though, since the rewrite is under way.

**Pull request merged**
