### PR TITLE
Add help page for keyboard shortcuts

### PR DESCRIPTION
**Pull request by GeraldJansen**

### CODE REVIEW

**Comment by ederag** [comment]
Sorry for the delay, but this is good, although some parts require more thoughts on my side.
(this is why it is not merged yet). Would you please reopen ?

**Comment by GeraldJansen** [comment]
New year, new priorities on my side. Feel free to do what you like with the commits.

**Comment by ederag** [comment]
Understood, and you already did a huge lot for this project.
But the commits disappeared because your branch has been deleted.

**Comment by GeraldJansen** [comment]
I believe the commits are still there. At least when I click on the links above I still see them.

**Comment by ederag** [comment]
OK, I still got them, 
let's hope github will smart enough to change the status to "merged" when they are merged in.

**Comment by ederag** [comment]
@GeraldJansen Both commits are integrated in #545.
Sorry it took so long. I misread something (too tired back then).
It could definitely have been merged right away; that's quality work, as usual !

**Comment by GeraldJansen** [comment]
Thanks! Looking forward to the upcoming release. Keep up the good work.

**Pull request closed without merging**
