### PR TITLE
Add independent completion for categories and tags

### PR DESCRIPTION
**Pull request by CendioOssman**
They are often not bound to specific activities so make sure all
recent ones are suggested. This is even more important when entering
a previously unseen activity.

### CODE REVIEW

**Comment by CendioOssman** [comment]
I assume the same fix is needed for the extension.

**Comment by axmachado** [comment]
It looks interesting... will try to test it.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

If you are still interested in working on the new codebase (repositories: hamster-lib/cli/gtk/dbus) we would be most thrilled. Please feel free to either open a new issue with the relevant repository and/or join the discussion on the [mailinglist](http://lists.projecthamster.org/listinfo.cgi/hamster-dev-projecthamster.org).
For more context please see our [website](projecthamster.org).

Thanks for your interest and support! Eric.

**Comment by ederag** [comment]
After a tentative merge:
https://github.com/ederag/hamster/tree/CendioOssman-completion
it increases the code duplication (with `hamster.lib.Fact` and `parse_fact`)
already present in the common ancestor.
And it might be because of wrong choices during merge
(please help if it is the case),
but it is impossible to search specifically for a tag by typing `#` as the first letter,
while this is possible in current master.
It does not find tags in the auto-completion configuration,
but both versions find "unseen" activities.

So it seems that the issues this PR was intending to solve
have been resolved in another way by PR #363.
Please comment here if I missed anything.

Your work was useful though,
because the separation between activity, category and tags searches is very interesting,
and besides, it has surely been silently been used by others meanwhile.

**Comment by ederag** [comment]
related: #12

**Comment by CendioOssman** [comment]
I think this is still needed in some form. This is just based on looking at the current code though, I haven't tested anything.

Please re-open the PR and I'll update the branch to something that works with the existing code.

**Comment by ederag** [comment]
Since another PR had to be used to complement this one,
it would be better to keep this one closed, with its current history.
Please open a new PR, linking to this one.

Some comments before you start coding:
1) Please start by identifying clear use cases where the current code fails.
    We need to gather a bunch of tests anyway.
2) Searching for category or tags separately *is* possible now:
  just start the search with `@` or `#` respectively
3) What does not work well is to search for two tags,
    because they have to be given in the correct order to be found.
    The search for tags should not depend on the order.
    Or could it be useful for some users to have some "priority" order ?
4) There is still a lot of code duplication with `hamster.lib.__init__.py`,
     that should be removed in the process.
    (search should be based on facts fields)

**Pull request closed without merging**
