### PR TITLE
Add some tooltips for overview buttons

### PR DESCRIPTION
**Pull request by GeraldJansen**
Add tooltips for the buttons on the overview header bar to improve discoverability for first time users (cf. #447)

### CODE REVIEW

**Comment by GeraldJansen** [comment]
Okay, think this is ready now.

**Comment by ederag** [comment]
Thanks, looks good !
A slight concern was that the `+` icon might mean either `Ctrl-N` or `Ctrl-R`, 
depending on the selection state.
This is the purpose of 357926a460efbb2b7ae46dfa58e8042470f75bec, please review.
It might be better to state the specific shortcut first (eg. `Ctrl-N or Ctrl-+`) instead of the reverse.
Please do make this change if you feel so.

**Comment by GeraldJansen** [comment]
Having different tooltips for the `+` icon, depending on whether or not an activity is selected, as well as multiple options for key strokes, could become confusing. Perhaps a single tooltip like "Add new (Ctrl-N) or resume selected (Ctrl-R) activity"  would be better. More detail could be given on the Input help page (eg. alternative `Ctrl-+` key, which btw is less convenient on an English keyboard, requiring also the Shft key).  It's a matter of opinion I suppose, so whichever you choose will be fine with me.

**Comment by ederag** [comment]
> Having different tooltips for the `+` icon, depending on whether or not an activity is selected, as well as multiple options for key strokes, could become confusing. Perhaps a single tooltip like "Add new (Ctrl-N) or resume selected (Ctrl-R) activity" would be better.

Interesting. 
Should the tooltip say what is going to happen if the item is activated now, 
or give a general information ?

gnome [guidelines](https://developer.gnome.org/hig-book/unstable/toolbars-labels-tooltips.html.en) did not tell much in this respect.

From [ux-planet](https://uxplanet.org/tooltips-in-ui-design-f63e117aa3d1)
> Contains static information
> Users don’t expect tooltips to change from one instance to the next, so they are unlikely to notice changes in dynamic content, such as status information.

Actually the same text is found [here](https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-tooltips-and-infotips), together with more extensive guidelines.

> "Add new (Ctrl-N) or resume selected (Ctrl-R) activity"

Yet this would be ambiguous: if an activity is selected, clicking the button will not add new.
it would be possible to say
```
Add activity (Ctrl-+)
If an activity is selected, clone (resume) this activity (equivalent to Ctrl-R)
otherwise create a new activity (equivalent to Ctrl-N)
```

The text has to be very clear to avoid this kind of [confusion](https://ux.stackexchange.com/questions/55324/should-a-tooltip-on-a-stateful-widget-describe-the-current-state-or-next-click-a?rq=1&newreg=531ee7d503dc4b36adfb0c62e095f79c#comment186653_55710).

Need to think. Right now saying what clicking the button will do seems adequate to me,
but you are right that a static tooltip is usually recommended.

Or maybe we should use a status bar instead ?

Need to think.

Renaming the "use-case" label to "design".

> Ctrl-+ key, which btw is less convenient on an English keyboard, requiring also the Shift key

`Right Ctrl - Numpad +` works too here, this is the one I'm using most often actually.

**Comment by GeraldJansen** [comment]
:+1: for being thorough! My final feedback/suggestion: simply use "Add activity (Ctrl-+)" as tooltip and leave the documentation of the Ctrl-N and Ctrl-R alternatives to the Input help page.

**Comment by ederag** [comment]
> simply use "Add activity (Ctrl-+)"

That would be good, and light.

Another option would be a mix of static and dynamic:
```
Add activity (Ctrl-+)
If an activity is selected, clone (resume) this activity (equivalent to Ctrl-R)
otherwise create a new activity (equivalent to Ctrl-N)
```
with an emphasis (bold face) on either "clone (resume)" or "new" depending on the selection state.

Perhaps a bit too much code for the benefit.
That's surely overthinking, but nice for the user ?

**Comment by GeraldJansen** [comment]
I've had a look at tooltips for various applications I use and they are universally very short. They should be hints rather than full documentation.

**Comment by ederag** [comment]
My proposition would be an [infotip](https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-tooltips-and-infotips) rather than a tooltip.
I agree that "Add activity (Ctrl-+)" would be more standard.
Yet the `+` button does two related but different things, that might deserve the infotip.

Let's take some time to let other users give their feelings on this subject.

**Comment by ederag** [comment]
Well, given the enthusiasm around my proposition,
rolled back, and adopted your suggestion.
This has the huge benefit to keep code simpler. Thanks !
Waiting for your check before merge.

**Comment by GeraldJansen** [comment]
Looks good to me.

**Comment by ederag** [comment]
That was super quick, thanks !

**Pull request merged**
